In [19]:
import scipy.io as sio
import os

from PIL import Image, ImageDraw
import cv2
import matplotlib.pyplot as plt

import numpy as np
import pandas as pd

import time
from pathlib import Path

action_list = pd.read_csv('~/HICO_rcnn/hico_det_dataset/action_list.csv')

In [34]:
# anno_bbox = sio.loadmat('160000_iCAN_ResNet50_HICO/detections_02.mat', squeeze_me=True)
anno_bbox = sio.loadmat('/home/jovyan/iCAN/Results/HICO_DET/1800000_iCAN_ResNet50_HICO/detections_02.mat', squeeze_me=True)

In [35]:
# image = cv2.imread('/home/jovyan/hico_20160224_det/images/test2015/HICO_test2015_00009734.jpg')
# print(image)
# plt.imshow(image)
# cv2.imshow("windows_name",image)
print(len(anno_bbox['all_boxes']))
anno_bbox['all_boxes']

102830


array([[array([223.82565308,  38.76403809, 478.63064575, 633.25756836]),
        array([ 33.43659973, 135.73394775, 497.14624023, 536.94525146]),
        4976, 0, 0.7023025155067444],
       [array([ 50.46954346,   0.        , 299.07095337, 405.1829834 ]),
        array([  0.        ,  86.14028931, 388.46112061, 434.38192749]),
        7891, 0, 0.5547191500663757],
       [array([207.11920166, 130.13825989, 376.40148926, 537.56402588]),
        array([ 22.09729004, 205.75259399, 308.39306641, 506.8286438 ]),
        1549, 0, 0.5253602862358093],
       ...,
       [array([303.57324219, 557.57995605, 312.74920654, 581.85900879]),
        array([ 65.58970642, 580.68469238,  97.2315979 , 616.2010498 ]),
        8545, 13, 2.059234715322375e-15],
       [array([303.57324219, 557.57995605, 312.74920654, 581.85900879]),
        array([298.00662231, 586.56054688, 357.28018188, 622.76098633]),
        8545, 13, 1.6285293671927594e-15],
       [array([303.57324219, 557.57995605, 312.74920654, 58

In [36]:
def generate_file_name(number):
    str_size = len(str(number))
    add_sero_number = 4-str_size
    name = '/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_0000' + '0' * add_sero_number + str(number) + '.jpg'
    return name

In [37]:
obj_list = action_list['object']
verb_list = action_list['verb']
nnn = 597
print(verb_list[nnn], ' ', obj_list[nnn])

pet   zebra


array([array([113.94587708, 125.61811829, 122.42951965, 150.76728821]),
       array([  0.        , 218.45680237, 243.97976685, 447.04052734]),
       7989, 0, 2.33815512729052e-06], dtype=object)

In [40]:
for info in anno_bbox['all_boxes']:
    if info[-1] > 0.5:
        image = Image.open(generate_file_name(info[2]))
        print(generate_file_name(info[2]))
        print('humna: ', info[0])
        print('object: ', info[1])
        draw =ImageDraw.Draw(image)
        
        # human
        h_x1 = info[0][0]
        h_x2 = info[0][1]
        h_y1 = info[0][2]
        h_y2 = info[0][3]
        draw.line(xy=[(h_x1, h_y1),(h_x2, h_y1),(h_x2, h_y2),(h_x1, h_y2),(h_x1, h_y1)], width = 1, fill = 'green')
        
        # object
        o_x1 = info[1][0]
        o_x2 = info[1][1]
        o_y1 = info[1][2]
        o_y2 = info[1][3]
        draw.line(xy=[(o_x1, o_y1),(o_x2, o_y1),(o_x2, o_y2),(o_x1, o_y2),(o_x1, o_y1)], width = 1, fill = 'blue')
        print(verb_list[info[3]] + ' ' + obj_list[info[3]])
        draw.text((10,10), verb_list[info[3]] + ' ' + obj_list[info[3]])
#         image.show()
        image.save( str(info[2]) + '_.jpg', "JPEG" )
        

/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_00004976.jpg
humna:  [223.82565308  38.76403809 478.63064575 633.25756836]
object:  [ 33.43659973 135.73394775 497.14624023 536.94525146]
board airplane
/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_00007891.jpg
humna:  [ 50.46954346   0.         299.07095337 405.1829834 ]
object:  [  0.          86.14028931 388.46112061 434.38192749]
board airplane
/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_00001549.jpg
humna:  [207.11920166 130.13825989 376.40148926 537.56402588]
object:  [ 22.09729004 205.75259399 308.39306641 506.8286438 ]
board airplane
/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_00000555.jpg
humna:  [109.66509247  91.92692566 262.86734009 386.73590088]
object:  [ 44.06190491 204.02938843 347.28637695 401.40457153]
direct airplane
/home/jovyan/iCAN/Data/hico_20160224_det/images/test2015/HICO_test2015_00005112.jpg
humna:  [223.298309

KeyboardInterrupt: 